version: '3.8'

services:
   catalog.api:
    build:
      context: .
      dockerfile: Catalog/Catalog.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5001:5000
   nginx:
    image: nginx
    container_name: nginx-1
    ports: 
     - 81:80

networks:
  dockernet:
    external: true